// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameClass = "t_class"

// Class mapped from table <t_class>
type Class struct {
	ID   string  `gorm:"column:id;primaryKey" json:"id"`
	Name *string `gorm:"column:name" json:"name"`
}

// TableName Class's table name
func (*Class) TableName() string {
	return TableNameClass
}
